---
#========================
# File tasks/main.yml
#
# Description:
#
# Author: Derek 'dRock' Halsey
#========================

- name: TEMPLATE | Template the domain.conf file
  become: true
  become_user: root
  template:
    src: domainName.conf.j2
    dest: /etc/nginx/sites-available/{{ nginx_domain.url }}.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: FILE | Link the domain.conf file to activate it
  become: true
  become_user: root
  file:
    src: /etc/nginx/sites-available/{{ nginx_domain.url }}.conf
    path: /etc/nginx/sites-enabled/{{ nginx_domain.url }}.conf
    state: link

- name: COMMAND | Reload nginx
  become: true
  become_user: root
  command: nginx -s reload
